name: node js
on: [push, pull_request]
jobs:
  build_1:
    name: build one
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12.x]
        os: [ubuntu-latest]
    steps:
      - name: Check out branch
        uses: actions/checkout@v2.0.0
      - name: Setup node
        uses: actions/setup-node@v1.1.0
        with:
          version: ${{ matrix.node_version }}
      - name: Run npm builds
        run: |
          npm install
          npm run build --if-present
          npm start
        
        
        
